name: "Send Email after Workflow"

on:
    workflow_dispatch:

jobs:
    send_email:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout Code"
              uses: actions/checkout@v2

            - name: "Setup Python"
              uses: actions/setup-python@v2
              with:
                python-version: '3.x'
            
            - name: "Install dependencies"
              run: python -m pip install --upgrage pip

            - name: "Send email by executing python script"
              run: python3 script.py
              env:
                WORKFLOW_NAME: ${{ github.workflow }}
                WORKFLOW_RUN_ID: ${{ github.run_id }}
                REPO_NAME: ${{ github.repository }}
                SENDER_PASS: ${{ secrets.SENDER_PASSWORD }}
                SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
                RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
                
